/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as EpisodesRouteImport } from './routes/episodes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BehindTheScenesRouteImport } from './routes/behind-the-scenes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTiktokLatestRouteImport } from './routes/api/tiktok/latest'
import { Route as ApiPodcastLatestRouteImport } from './routes/api/podcast/latest'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesRoute = EpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BehindTheScenesRoute = BehindTheScenesRouteImport.update({
  id: '/behind-the-scenes',
  path: '/behind-the-scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTiktokLatestRoute = ApiTiktokLatestRouteImport.update({
  id: '/api/tiktok/latest',
  path: '/api/tiktok/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPodcastLatestRoute = ApiPodcastLatestRouteImport.update({
  id: '/api/podcast/latest',
  path: '/api/podcast/latest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/behind-the-scenes': typeof BehindTheScenesRoute
  '/contact': typeof ContactRoute
  '/episodes': typeof EpisodesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/podcast/latest': typeof ApiPodcastLatestRoute
  '/api/tiktok/latest': typeof ApiTiktokLatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/behind-the-scenes': typeof BehindTheScenesRoute
  '/contact': typeof ContactRoute
  '/episodes': typeof EpisodesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/podcast/latest': typeof ApiPodcastLatestRoute
  '/api/tiktok/latest': typeof ApiTiktokLatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/behind-the-scenes': typeof BehindTheScenesRoute
  '/contact': typeof ContactRoute
  '/episodes': typeof EpisodesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/podcast/latest': typeof ApiPodcastLatestRoute
  '/api/tiktok/latest': typeof ApiTiktokLatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/behind-the-scenes'
    | '/contact'
    | '/episodes'
    | '/shop'
    | '/sitemap.xml'
    | '/api/podcast/latest'
    | '/api/tiktok/latest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/behind-the-scenes'
    | '/contact'
    | '/episodes'
    | '/shop'
    | '/sitemap.xml'
    | '/api/podcast/latest'
    | '/api/tiktok/latest'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/behind-the-scenes'
    | '/contact'
    | '/episodes'
    | '/shop'
    | '/sitemap.xml'
    | '/api/podcast/latest'
    | '/api/tiktok/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BehindTheScenesRoute: typeof BehindTheScenesRoute
  ContactRoute: typeof ContactRoute
  EpisodesRoute: typeof EpisodesRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPodcastLatestRoute: typeof ApiPodcastLatestRoute
  ApiTiktokLatestRoute: typeof ApiTiktokLatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes': {
      id: '/episodes'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof EpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behind-the-scenes': {
      id: '/behind-the-scenes'
      path: '/behind-the-scenes'
      fullPath: '/behind-the-scenes'
      preLoaderRoute: typeof BehindTheScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tiktok/latest': {
      id: '/api/tiktok/latest'
      path: '/api/tiktok/latest'
      fullPath: '/api/tiktok/latest'
      preLoaderRoute: typeof ApiTiktokLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podcast/latest': {
      id: '/api/podcast/latest'
      path: '/api/podcast/latest'
      fullPath: '/api/podcast/latest'
      preLoaderRoute: typeof ApiPodcastLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BehindTheScenesRoute: BehindTheScenesRoute,
  ContactRoute: ContactRoute,
  EpisodesRoute: EpisodesRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPodcastLatestRoute: ApiPodcastLatestRoute,
  ApiTiktokLatestRoute: ApiTiktokLatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
